spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username=${DATASOURCE_USER}
spring.datasource.password=${DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
server.servlet.context-path = /api/v1.0
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true

aws.access.key = AKIARYEUCTYAMJLRAC5V
aws.secret.key = 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
aws.region = eu-north-1
aws.bucket.name = billing-software-scbushan06

#http://localhost:8080/api/v1.0/

jwt.secret.key = 1571f36a1c4a188cb3e99726370f26dfbdc1f9790832a2b232de945f900c09ce

razorpay.key.id = rzp_test_RLJ5r60hURorME
razorpay.key.secret = uE1y4HSo7bhBi05LTuQcC1qk


frontend.url = ${FRONTEND_URL}




